#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningPlatformData.DBML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tutorialDB")]
	public partial class LearningDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcontent(content instance);
    partial void Updatecontent(content instance);
    partial void Deletecontent(content instance);
    partial void InsertContentMedia(ContentMedia instance);
    partial void UpdateContentMedia(ContentMedia instance);
    partial void DeleteContentMedia(ContentMedia instance);
    partial void InsertContentStaging(ContentStaging instance);
    partial void UpdateContentStaging(ContentStaging instance);
    partial void DeleteContentStaging(ContentStaging instance);
    partial void Insertcourse(course instance);
    partial void Updatecourse(course instance);
    partial void Deletecourse(course instance);
    partial void InsertMedia(Media instance);
    partial void UpdateMedia(Media instance);
    partial void DeleteMedia(Media instance);
    partial void Inserttopic(topic instance);
    partial void Updatetopic(topic instance);
    partial void Deletetopic(topic instance);
    #endregion
		
		public LearningDataClassesDataContext() : 
				base(global::LearningPlatformData.Properties.Settings.Default.tutorialDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LearningDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<content> contents
		{
			get
			{
				return this.GetTable<content>();
			}
		}
		
		public System.Data.Linq.Table<ContentMedia> ContentMedias
		{
			get
			{
				return this.GetTable<ContentMedia>();
			}
		}
		
		public System.Data.Linq.Table<ContentStaging> ContentStagings
		{
			get
			{
				return this.GetTable<ContentStaging>();
			}
		}
		
		public System.Data.Linq.Table<course> courses
		{
			get
			{
				return this.GetTable<course>();
			}
		}
		
		public System.Data.Linq.Table<Media> Medias
		{
			get
			{
				return this.GetTable<Media>();
			}
		}
		
		public System.Data.Linq.Table<topic> topics
		{
			get
			{
				return this.GetTable<topic>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_GetTopicsByCourse")]
		public ISingleResult<proc_GetTopicsByCourseResult> proc_GetTopicsByCourse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string courseName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseName);
			return ((ISingleResult<proc_GetTopicsByCourseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_GetContentByTopicId")]
		public ISingleResult<proc_GetContentByTopicIdResult> proc_GetContentByTopicId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> topicId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), topicId);
			return ((ISingleResult<proc_GetContentByTopicIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.content")]
	public partial class content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _content_id;
		
		private System.Nullable<int> _topic_id;
		
		private string _content_type;
		
		private string _content_body;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private string _title;
		
		private string _raw_body;
		
		private EntitySet<ContentMedia> _ContentMedias;
		
		private EntitySet<ContentStaging> _ContentStagings;
		
		private EntityRef<topic> _topic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontent_idChanging(int value);
    partial void Oncontent_idChanged();
    partial void Ontopic_idChanging(System.Nullable<int> value);
    partial void Ontopic_idChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void Oncontent_bodyChanging(string value);
    partial void Oncontent_bodyChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onraw_bodyChanging(string value);
    partial void Onraw_bodyChanged();
    #endregion
		
		public content()
		{
			this._ContentMedias = new EntitySet<ContentMedia>(new Action<ContentMedia>(this.attach_ContentMedias), new Action<ContentMedia>(this.detach_ContentMedias));
			this._ContentStagings = new EntitySet<ContentStaging>(new Action<ContentStaging>(this.attach_ContentStagings), new Action<ContentStaging>(this.detach_ContentStagings));
			this._topic = default(EntityRef<topic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int content_id
		{
			get
			{
				return this._content_id;
			}
			set
			{
				if ((this._content_id != value))
				{
					this.Oncontent_idChanging(value);
					this.SendPropertyChanging();
					this._content_id = value;
					this.SendPropertyChanged("content_id");
					this.Oncontent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", DbType="Int")]
		public System.Nullable<int> topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					if (this._topic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontopic_idChanging(value);
					this.SendPropertyChanging();
					this._topic_id = value;
					this.SendPropertyChanged("topic_id");
					this.Ontopic_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string content_body
		{
			get
			{
				return this._content_body;
			}
			set
			{
				if ((this._content_body != value))
				{
					this.Oncontent_bodyChanging(value);
					this.SendPropertyChanging();
					this._content_body = value;
					this.SendPropertyChanged("content_body");
					this.Oncontent_bodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raw_body", DbType="NVarChar(MAX)")]
		public string raw_body
		{
			get
			{
				return this._raw_body;
			}
			set
			{
				if ((this._raw_body != value))
				{
					this.Onraw_bodyChanging(value);
					this.SendPropertyChanging();
					this._raw_body = value;
					this.SendPropertyChanged("raw_body");
					this.Onraw_bodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="content_ContentMedia", Storage="_ContentMedias", ThisKey="content_id", OtherKey="content_id")]
		public EntitySet<ContentMedia> ContentMedias
		{
			get
			{
				return this._ContentMedias;
			}
			set
			{
				this._ContentMedias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="content_ContentStaging", Storage="_ContentStagings", ThisKey="content_id", OtherKey="content_id")]
		public EntitySet<ContentStaging> ContentStagings
		{
			get
			{
				return this._ContentStagings;
			}
			set
			{
				this._ContentStagings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="topic_content", Storage="_topic", ThisKey="topic_id", OtherKey="topic_id", IsForeignKey=true)]
		public topic topic
		{
			get
			{
				return this._topic.Entity;
			}
			set
			{
				topic previousValue = this._topic.Entity;
				if (((previousValue != value) 
							|| (this._topic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._topic.Entity = null;
						previousValue.contents.Remove(this);
					}
					this._topic.Entity = value;
					if ((value != null))
					{
						value.contents.Add(this);
						this._topic_id = value.topic_id;
					}
					else
					{
						this._topic_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("topic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContentMedias(ContentMedia entity)
		{
			this.SendPropertyChanging();
			entity.content = this;
		}
		
		private void detach_ContentMedias(ContentMedia entity)
		{
			this.SendPropertyChanging();
			entity.content = null;
		}
		
		private void attach_ContentStagings(ContentStaging entity)
		{
			this.SendPropertyChanging();
			entity.content = this;
		}
		
		private void detach_ContentStagings(ContentStaging entity)
		{
			this.SendPropertyChanging();
			entity.content = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContentMedia")]
	public partial class ContentMedia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _content_id;
		
		private int _media_id;
		
		private System.Nullable<int> _media_order;
		
		private EntityRef<content> _content;
		
		private EntityRef<Media> _Media;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontent_idChanging(int value);
    partial void Oncontent_idChanged();
    partial void Onmedia_idChanging(int value);
    partial void Onmedia_idChanged();
    partial void Onmedia_orderChanging(System.Nullable<int> value);
    partial void Onmedia_orderChanged();
    #endregion
		
		public ContentMedia()
		{
			this._content = default(EntityRef<content>);
			this._Media = default(EntityRef<Media>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int content_id
		{
			get
			{
				return this._content_id;
			}
			set
			{
				if ((this._content_id != value))
				{
					if (this._content.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontent_idChanging(value);
					this.SendPropertyChanging();
					this._content_id = value;
					this.SendPropertyChanged("content_id");
					this.Oncontent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int media_id
		{
			get
			{
				return this._media_id;
			}
			set
			{
				if ((this._media_id != value))
				{
					if (this._Media.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmedia_idChanging(value);
					this.SendPropertyChanging();
					this._media_id = value;
					this.SendPropertyChanged("media_id");
					this.Onmedia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_order", DbType="Int")]
		public System.Nullable<int> media_order
		{
			get
			{
				return this._media_order;
			}
			set
			{
				if ((this._media_order != value))
				{
					this.Onmedia_orderChanging(value);
					this.SendPropertyChanging();
					this._media_order = value;
					this.SendPropertyChanged("media_order");
					this.Onmedia_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="content_ContentMedia", Storage="_content", ThisKey="content_id", OtherKey="content_id", IsForeignKey=true)]
		public content content
		{
			get
			{
				return this._content.Entity;
			}
			set
			{
				content previousValue = this._content.Entity;
				if (((previousValue != value) 
							|| (this._content.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._content.Entity = null;
						previousValue.ContentMedias.Remove(this);
					}
					this._content.Entity = value;
					if ((value != null))
					{
						value.ContentMedias.Add(this);
						this._content_id = value.content_id;
					}
					else
					{
						this._content_id = default(int);
					}
					this.SendPropertyChanged("content");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Media_ContentMedia", Storage="_Media", ThisKey="media_id", OtherKey="media_id", IsForeignKey=true)]
		public Media Media
		{
			get
			{
				return this._Media.Entity;
			}
			set
			{
				Media previousValue = this._Media.Entity;
				if (((previousValue != value) 
							|| (this._Media.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Media.Entity = null;
						previousValue.ContentMedias.Remove(this);
					}
					this._Media.Entity = value;
					if ((value != null))
					{
						value.ContentMedias.Add(this);
						this._media_id = value.media_id;
					}
					else
					{
						this._media_id = default(int);
					}
					this.SendPropertyChanged("Media");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContentStaging")]
	public partial class ContentStaging : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _staging_id;
		
		private System.Nullable<int> _content_id;
		
		private string _title;
		
		private string _raw_body;
		
		private string _content_type;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private EntityRef<content> _content;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstaging_idChanging(int value);
    partial void Onstaging_idChanged();
    partial void Oncontent_idChanging(System.Nullable<int> value);
    partial void Oncontent_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onraw_bodyChanging(string value);
    partial void Onraw_bodyChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    #endregion
		
		public ContentStaging()
		{
			this._content = default(EntityRef<content>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staging_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int staging_id
		{
			get
			{
				return this._staging_id;
			}
			set
			{
				if ((this._staging_id != value))
				{
					this.Onstaging_idChanging(value);
					this.SendPropertyChanging();
					this._staging_id = value;
					this.SendPropertyChanged("staging_id");
					this.Onstaging_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_id", DbType="Int")]
		public System.Nullable<int> content_id
		{
			get
			{
				return this._content_id;
			}
			set
			{
				if ((this._content_id != value))
				{
					if (this._content.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontent_idChanging(value);
					this.SendPropertyChanging();
					this._content_id = value;
					this.SendPropertyChanged("content_id");
					this.Oncontent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raw_body", DbType="NVarChar(MAX)")]
		public string raw_body
		{
			get
			{
				return this._raw_body;
			}
			set
			{
				if ((this._raw_body != value))
				{
					this.Onraw_bodyChanging(value);
					this.SendPropertyChanging();
					this._raw_body = value;
					this.SendPropertyChanged("raw_body");
					this.Onraw_bodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="VarChar(50)")]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="content_ContentStaging", Storage="_content", ThisKey="content_id", OtherKey="content_id", IsForeignKey=true)]
		public content content
		{
			get
			{
				return this._content.Entity;
			}
			set
			{
				content previousValue = this._content.Entity;
				if (((previousValue != value) 
							|| (this._content.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._content.Entity = null;
						previousValue.ContentStagings.Remove(this);
					}
					this._content.Entity = value;
					if ((value != null))
					{
						value.ContentStagings.Add(this);
						this._content_id = value.content_id;
					}
					else
					{
						this._content_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("content");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.courses")]
	public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _course_id;
		
		private string _course_name;
		
		private string _description;
		
		private EntitySet<topic> _topics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncourse_idChanging(int value);
    partial void Oncourse_idChanged();
    partial void Oncourse_nameChanging(string value);
    partial void Oncourse_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public course()
		{
			this._topics = new EntitySet<topic>(new Action<topic>(this.attach_topics), new Action<topic>(this.detach_topics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this.Oncourse_nameChanging(value);
					this.SendPropertyChanging();
					this._course_name = value;
					this.SendPropertyChanged("course_name");
					this.Oncourse_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_topic", Storage="_topics", ThisKey="course_id", OtherKey="course_id")]
		public EntitySet<topic> topics
		{
			get
			{
				return this._topics;
			}
			set
			{
				this._topics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_topics(topic entity)
		{
			this.SendPropertyChanging();
			entity.course = this;
		}
		
		private void detach_topics(topic entity)
		{
			this.SendPropertyChanging();
			entity.course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Media")]
	public partial class Media : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _media_id;
		
		private string _file_path;
		
		private string _alt_text;
		
		private string _media_type;
		
		private System.Nullable<System.DateTime> _uploaded_at;
		
		private EntitySet<ContentMedia> _ContentMedias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmedia_idChanging(int value);
    partial void Onmedia_idChanged();
    partial void Onfile_pathChanging(string value);
    partial void Onfile_pathChanged();
    partial void Onalt_textChanging(string value);
    partial void Onalt_textChanged();
    partial void Onmedia_typeChanging(string value);
    partial void Onmedia_typeChanged();
    partial void Onuploaded_atChanging(System.Nullable<System.DateTime> value);
    partial void Onuploaded_atChanged();
    #endregion
		
		public Media()
		{
			this._ContentMedias = new EntitySet<ContentMedia>(new Action<ContentMedia>(this.attach_ContentMedias), new Action<ContentMedia>(this.detach_ContentMedias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int media_id
		{
			get
			{
				return this._media_id;
			}
			set
			{
				if ((this._media_id != value))
				{
					this.Onmedia_idChanging(value);
					this.SendPropertyChanging();
					this._media_id = value;
					this.SendPropertyChanged("media_id");
					this.Onmedia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_path", DbType="NVarChar(255)")]
		public string file_path
		{
			get
			{
				return this._file_path;
			}
			set
			{
				if ((this._file_path != value))
				{
					this.Onfile_pathChanging(value);
					this.SendPropertyChanging();
					this._file_path = value;
					this.SendPropertyChanged("file_path");
					this.Onfile_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt_text", DbType="NVarChar(255)")]
		public string alt_text
		{
			get
			{
				return this._alt_text;
			}
			set
			{
				if ((this._alt_text != value))
				{
					this.Onalt_textChanging(value);
					this.SendPropertyChanging();
					this._alt_text = value;
					this.SendPropertyChanged("alt_text");
					this.Onalt_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_type", DbType="VarChar(50)")]
		public string media_type
		{
			get
			{
				return this._media_type;
			}
			set
			{
				if ((this._media_type != value))
				{
					this.Onmedia_typeChanging(value);
					this.SendPropertyChanging();
					this._media_type = value;
					this.SendPropertyChanged("media_type");
					this.Onmedia_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploaded_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> uploaded_at
		{
			get
			{
				return this._uploaded_at;
			}
			set
			{
				if ((this._uploaded_at != value))
				{
					this.Onuploaded_atChanging(value);
					this.SendPropertyChanging();
					this._uploaded_at = value;
					this.SendPropertyChanged("uploaded_at");
					this.Onuploaded_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Media_ContentMedia", Storage="_ContentMedias", ThisKey="media_id", OtherKey="media_id")]
		public EntitySet<ContentMedia> ContentMedias
		{
			get
			{
				return this._ContentMedias;
			}
			set
			{
				this._ContentMedias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContentMedias(ContentMedia entity)
		{
			this.SendPropertyChanging();
			entity.Media = this;
		}
		
		private void detach_ContentMedias(ContentMedia entity)
		{
			this.SendPropertyChanging();
			entity.Media = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.topics")]
	public partial class topic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _topic_id;
		
		private System.Nullable<int> _course_id;
		
		private string _topic_title;
		
		private int _topic_order;
		
		private EntitySet<content> _contents;
		
		private EntityRef<course> _course;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontopic_idChanging(int value);
    partial void Ontopic_idChanged();
    partial void Oncourse_idChanging(System.Nullable<int> value);
    partial void Oncourse_idChanged();
    partial void Ontopic_titleChanging(string value);
    partial void Ontopic_titleChanged();
    partial void Ontopic_orderChanging(int value);
    partial void Ontopic_orderChanged();
    #endregion
		
		public topic()
		{
			this._contents = new EntitySet<content>(new Action<content>(this.attach_contents), new Action<content>(this.detach_contents));
			this._course = default(EntityRef<course>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					this.Ontopic_idChanging(value);
					this.SendPropertyChanging();
					this._topic_id = value;
					this.SendPropertyChanged("topic_id");
					this.Ontopic_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="Int")]
		public System.Nullable<int> course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					if (this._course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string topic_title
		{
			get
			{
				return this._topic_title;
			}
			set
			{
				if ((this._topic_title != value))
				{
					this.Ontopic_titleChanging(value);
					this.SendPropertyChanging();
					this._topic_title = value;
					this.SendPropertyChanged("topic_title");
					this.Ontopic_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_order", DbType="Int NOT NULL")]
		public int topic_order
		{
			get
			{
				return this._topic_order;
			}
			set
			{
				if ((this._topic_order != value))
				{
					this.Ontopic_orderChanging(value);
					this.SendPropertyChanging();
					this._topic_order = value;
					this.SendPropertyChanged("topic_order");
					this.Ontopic_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="topic_content", Storage="_contents", ThisKey="topic_id", OtherKey="topic_id")]
		public EntitySet<content> contents
		{
			get
			{
				return this._contents;
			}
			set
			{
				this._contents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_topic", Storage="_course", ThisKey="course_id", OtherKey="course_id", IsForeignKey=true)]
		public course course
		{
			get
			{
				return this._course.Entity;
			}
			set
			{
				course previousValue = this._course.Entity;
				if (((previousValue != value) 
							|| (this._course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course.Entity = null;
						previousValue.topics.Remove(this);
					}
					this._course.Entity = value;
					if ((value != null))
					{
						value.topics.Add(this);
						this._course_id = value.course_id;
					}
					else
					{
						this._course_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("course");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_contents(content entity)
		{
			this.SendPropertyChanging();
			entity.topic = this;
		}
		
		private void detach_contents(content entity)
		{
			this.SendPropertyChanging();
			entity.topic = null;
		}
	}
	
	public partial class proc_GetTopicsByCourseResult
	{
		
		private int _topic_id;
		
		private string _topic_title;
		
		public proc_GetTopicsByCourseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", DbType="Int NOT NULL")]
		public int topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					this._topic_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_title", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string topic_title
		{
			get
			{
				return this._topic_title;
			}
			set
			{
				if ((this._topic_title != value))
				{
					this._topic_title = value;
				}
			}
		}
	}
	
	public partial class proc_GetContentByTopicIdResult
	{
		
		private int _content_id;
		
		private System.Nullable<int> _topic_id;
		
		private string _content_type;
		
		private string _title;
		
		private string _raw_body;
		
		private System.Nullable<int> _media_id;
		
		private string _file_path;
		
		private string _alt_text;
		
		private string _media_type;
		
		private System.Nullable<int> _media_order;
		
		public proc_GetContentByTopicIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_id", DbType="Int NOT NULL")]
		public int content_id
		{
			get
			{
				return this._content_id;
			}
			set
			{
				if ((this._content_id != value))
				{
					this._content_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", DbType="Int")]
		public System.Nullable<int> topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					this._topic_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this._content_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raw_body", DbType="NVarChar(MAX)")]
		public string raw_body
		{
			get
			{
				return this._raw_body;
			}
			set
			{
				if ((this._raw_body != value))
				{
					this._raw_body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_id", DbType="Int")]
		public System.Nullable<int> media_id
		{
			get
			{
				return this._media_id;
			}
			set
			{
				if ((this._media_id != value))
				{
					this._media_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_path", DbType="NVarChar(255)")]
		public string file_path
		{
			get
			{
				return this._file_path;
			}
			set
			{
				if ((this._file_path != value))
				{
					this._file_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt_text", DbType="NVarChar(255)")]
		public string alt_text
		{
			get
			{
				return this._alt_text;
			}
			set
			{
				if ((this._alt_text != value))
				{
					this._alt_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_type", DbType="VarChar(50)")]
		public string media_type
		{
			get
			{
				return this._media_type;
			}
			set
			{
				if ((this._media_type != value))
				{
					this._media_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media_order", DbType="Int")]
		public System.Nullable<int> media_order
		{
			get
			{
				return this._media_order;
			}
			set
			{
				if ((this._media_order != value))
				{
					this._media_order = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
