FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
WORKDIR /inetpub/wwwroot
COPY ./bin/Release/PublishOutput .
EXPOSE 80
ENTRYPOINT ["C:\\Windows\\System32\\inetsrv\\w3wp.exe", "-a", "\\inetpub\\wwwroot"]